before_script:
- bundle exec rake db:migrate RAILS_ENV=test
branches:
  only:
  - master
  - develop
  - deploy
addons:
  code_climate:
    repo_token: a87c36225345cd75f1be6a24cc3ffdec4461d603c9f92ff98a80c19af8f81fa7
language: ruby
rvm:
- 2.2.1
notifications:
  email:
    recipients:
    - furquim.axs@gmail.com
after_success:
 - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy/id_rsa_ecn_travis -d -a -out config/deploy/id_rsa"
 - eval $(ssh-agent)
 - chmod 600 config/deploy/deploy_id_rsa
 - ssh-add config/deploy/deploy_id_rsa
 - gem install capistrano-rails
 - cap production deploy

env:
  global:
    secure: eBDWRrwxxufdSJQuHH54V4MzBu2cyMYDUkA3vHq24SCxC8cD8mrVGLMlEnxjRDmItc3Yz3HjiQRrQxFhqhzCpC+awZG6u/6M8rYLQa2DiImD+cJ1+GeYpqm4nGC9iqojYmJp0E4KvpFqRE5DqPKtssSNw3ugPa7zjnoDppisdt48xedTl1ZUWVMRU8lcaj2W9a9K1MNF0+Qp1lQJIdtN8UgO4FY+edIlpN2nm4ed6PuhcONz+OobZC838EgH4d//kGY0mExsWQRPnhX/3zVx7GFNq7OE8p9jO5PYzx3oUOOVs/+noMDqelpmxepfmebRUghxs3SL5/ygASpFLErRQj9CjtUKxMAXbVUWw8SbKbcI2bIDXATLQOn9DR8xjocIOhdbxxULARR1rFa3/vEkfeYMgracZLt/aZ7kWBxsp4CgKcfdzcUkZNjfaNd+nNfpffSmt524uvyD/RF+Kxodq8fQQ2zH8QHMJcIdJhZ1Ovod1qIIq5ywuq7OB7hqZhRJOIFVEEeb/0A0MtUl3F2y/BWzEQn2bMGcrsgC9tCP4kzo0tZyfZBRC7y6n1ALF4fZjgyVaW/pkc0PJuN6kNAX5S/xvSi7gMxvPH6yrZMqeN5KVq7QfkhZqSlQO2HH58XcGGt4ry3q4fL++7co66MYaSDK0eZSTjjroIaonLzpQFQ=
